apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: assisted-service-krrl
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: assisted-service-krrl
    app.kubernetes.io/part-of: assisted-service
  name: assisted-service-krrl
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    app.kubernetes.io/instance: assisted-service-krrl
status:
  loadBalancer: {}
